server.port=8084
spring.application.name=recommendation-service

spring.datasource.url=jdbc:mysql://localhost:3306/recommendation_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=my-secret-key-1234567890-my-secret-key-1234567890-movie-streaming-app
tmdb.api.key=3fd2be6f0c70a2a598f084ddfb75487c
tmdb.base.url=https://api.themoviedb.org/3
watchlist.service.url=http://localhost:8082/api/watchlist
